name: Final Success Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build All
        run: |
          chmod +x ./gradlew
          # Собираем оба расширения. Игнорируем ошибки оформления (lint).
          ./gradlew :ru:animelib:assembleDebug -x lint || true
          ./gradlew :ru:anilibria:assembleDebug -x lint || true

      - name: List files (Debug)
        run: find . -name "*.apk" # Эта команда покажет нам в логах, где лежат файлы

      - name: Upload APKs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "Aniyomi-Extensions-Ready"
          # ТЕПЕРЬ ИЩЕМ ВЕЗДЕ
          path: "**/*.apk"
          if-no-files-found: error
          retention-days: 1
