name: Build My AnimeLib

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build AnimeLib
        run: |
          chmod +x ./gradlew
          # Эта команда найдет правильное имя проекта сама
          ./gradlew assembleDebug -Psubset=ru-animelib || ./gradlew :ru-animelib:assembleDebug || ./gradlew :ru:animelib:assembleDebug || ./gradlew assembleDebug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: "AnimeLib-Custom-APK"
          path: "**/build/outputs/apk/debug/*.apk"
          retention-days: 1
