name: Build My AnimeLib

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build AnimeLib
        run: |
          chmod +x ./gradlew
          # Собираем AnimeLib и ПРИНУДИТЕЛЬНО отключаем проверки (lint)
          ./gradlew :src:ru:animelib:assembleDebug -x lint -x test --stacktrace

      - name: Upload APK
        if: always() # Загрузить файл даже если будут предупреждения
        uses: actions/upload-artifact@v4
        with:
          name: "AnimeLib-Custom-APK"
          # Ищем файл во всех папках, чтобы точно найти его
          path: "**/*.apk"
          if-no-files-found: error
          retention-days: 1
